version: '3'
services:
  frontend:
    build: .
    ports:
      - '8888:80'
    environment:
      - PLACES_API_URL=http://host.docker.internal:8080
      - TILES_API_URL=http://host.docker.internal:4000
      - MARTIN_API_URL=http://host.docker.internal:3000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
