version: '3.8'
services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8888:8888"
    environment:
      # Use host.docker.internal to reach services running on the host machine (or in other compose stacks via mapped ports)
      # Assuming 'places-scraper' is running and exposing port 3000 on localhost
      - PLACES_API_URL=http://host.docker.internal:8080
      # Tileserver is running in this same compose stack, so we can address it by service name
      - TILES_API_URL=http://tileserver:8080
      - MARTIN_API_URL=http://host.docker.internal:3000
      - KEYCLOAK_URL=http://localhost:8081
      - CHOKIDAR_USEPOLLING=true 
    command: sh -c "npm install && npm run dev -- --host"
    restart: always
    depends_on:
      - tileserver
      # Removed scraper dependency as it's now external

  tileserver:
    image: maptiler/tileserver-gl
    container_name: tileserver
    ports:
      - "4000:8080"
    volumes:
      - /Users/kaloyanivanov/Personal-SRV/apis/grid-service/tiles:/data
      - /Users/kaloyanivanov/Personal-SRV/apis/grid-service/config.json:/config.json
    command: "--config /config.json"


